# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161007_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 10, 7, 11, 24, 9, 814000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
